### ISSUE TITLE
 Build command failed

### ISSUE THREAD

**Issue by YangTca** [lightweh/FaceDetection#2]
您好 请问这是什么原因啊  报错信息这是
Caused by: Build command failed.
Error while executing process C:\Users\87945\AppData\Local\Android\Sdk\cmake\3.6.4111459\bin\cmake.exe with arguments {--build F:\pyapplication\app\.cxx\cmake\debug\armeabi-v7a --target native-lib}

ninja: error: '../../../../src/main/cpp/opencv/libs/armeabi-v7a/libopencv_java3.so', needed by '../../../../build/intermediates/cmake/debug/obj/armeabi-v7a/libnative-lib.so', missing and no known rule to make it

	at com.android.build.gradle.internal.cxx.process.ProcessOutputJunction.execute(ProcessOutputJunction.kt:79)
	at com.android.build.gradle.internal.cxx.process.ProcessOutputJunction.execute(ProcessOutputJunction.kt:120)
	at com.android.build.gradle.tasks.ExternalNativeBuildTask.executeProcessBatch(ExternalNativeBuildTask.java:471)
	at com.android.build.gradle.tasks.ExternalNativeBuildTask.buildImpl(ExternalNativeBuildTask.java:207)
	at com.android.build.gradle.tasks.ExternalNativeBuildTask.doTaskAction(ExternalNativeBuildTask.java:107)
	at com.android.build.gradle.internal.tasks.NonIncrementalTask$taskAction$$inlined$recordTaskAction$1.invoke(AndroidVariantTask.kt:51)
	at com.android.build.gradle.internal.tasks.NonIncrementalTask$taskAction$$inlined$recordTaskAction$1.invoke(AndroidVariantTask.kt:31)
	at com.android.build.gradle.internal.tasks.Blocks.recordSpan(Blocks.java:91)
	at com.android.build.gradle.internal.tasks.NonIncrementalTask.taskAction(NonIncrementalTask.kt:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:103)
	... 91 more

**Comment by JiajiaHuang** [comment]
更换低版本，测试成功：
Android Gradle Plugin:3.5.4
Gradle vesion:5.4.1
Compile Sdk Version:28
Build Tools Version:28.0.3
NDK Version:21.1.6352462

**Comment by CMingTseng** [comment]
> 您好 请问这是什么原因啊 报错信息这是 Caused by: Build command failed. Error while executing process C:\Users\87945\AppData\Local\Android\Sdk\cmake\3.6.4111459\bin\cmake.exe with arguments {--build F:\pyapplication\app.cxx\cmake\debug\armeabi-v7a --target native-lib}
> 
> ninja: error: '../../../../src/main/cpp/opencv/libs/armeabi-v7a/libopencv_java3.so', needed by '../../../../build/intermediates/cmake/debug/obj/armeabi-v7a/libnative-lib.so', missing and no known rule to make it
> 
> ```
> at com.android.build.gradle.internal.cxx.process.ProcessOutputJunction.execute(ProcessOutputJunction.kt:79)
> at com.android.build.gradle.internal.cxx.process.ProcessOutputJunction.execute(ProcessOutputJunction.kt:120)
> at com.android.build.gradle.tasks.ExternalNativeBuildTask.executeProcessBatch(ExternalNativeBuildTask.java:471)
> at com.android.build.gradle.tasks.ExternalNativeBuildTask.buildImpl(ExternalNativeBuildTask.java:207)
> at com.android.build.gradle.tasks.ExternalNativeBuildTask.doTaskAction(ExternalNativeBuildTask.java:107)
> at com.android.build.gradle.internal.tasks.NonIncrementalTask$taskAction$$inlined$recordTaskAction$1.invoke(AndroidVariantTask.kt:51)
> at com.android.build.gradle.internal.tasks.NonIncrementalTask$taskAction$$inlined$recordTaskAction$1.invoke(AndroidVariantTask.kt:31)
> at com.android.build.gradle.internal.tasks.Blocks.recordSpan(Blocks.java:91)
> at com.android.build.gradle.internal.tasks.NonIncrementalTask.taskAction(NonIncrementalTask.kt:34)
> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> at java.lang.reflect.Method.invoke(Method.java:498)
> at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:103)
> ... 91 more
> ```

Dear Sir

i fork this  project  &  modify it 

you can check it 

or  waiting  PR 

THX

**Comment by CMingTseng** [comment]
> 更换低版本，测试成功： Android Gradle Plugin:3.5.4 Gradle vesion:5.4.1 Compile Sdk Version:28 Build Tools Version:28.0.3 NDK Version:21.1.6352462

Dear Sir

i fork this  project  &  modify it 

you can check it 

or  waiting  PR 

THX
